/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
    id("io.freefair.lombok") version "8.1.0"
}

//repositories {
//    mavenLocal()
//    maven {
//        url = uri("https://repo.maven.apache.org/maven2/")
//    }
//}


repositories {
    mavenCentral()
}


dependencies {
    api("org.springframework.boot:spring-boot-starter-data-jpa:3.0.4")
    api("org.springframework.boot:spring-boot-starter-security:3.0.4")
    api("org.springframework.boot:spring-boot-starter-thymeleaf:3.0.4")
    api("org.springframework.boot:spring-boot-starter-web:3.0.4")
    api("org.thymeleaf.extras:thymeleaf-extras-springsecurity6:3.1.1.RELEASE")
    api("org.springframework.boot:spring-boot-starter-validation:3.0.5")
    api("org.projectlombok:lombok:1.18.26")
    api("com.fasterxml.jackson.core:jackson-core:2.14.2")
    api("org.modelmapper:modelmapper:3.1.1")
    runtimeOnly("org.springframework.boot:spring-boot-devtools:3.0.4")
    runtimeOnly("com.mysql:mysql-connector-j:8.0.32")
    testImplementation("org.springframework.boot:spring-boot-starter-test:3.0.4")
    testImplementation("org.springframework.security:spring-security-test:6.0.2")
}

group = "me.niallmurray"
version = "0.0.1-SNAPSHOT"
description = "Slipstream"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
